version: '3.8'

services:
  whatsapp-bridge:
    build:
      context: ./whatsapp-bridge
      dockerfile: Dockerfile
    image: rhv044/whatsapp-bridge:prod
    container_name: whatsapp-bridge
    expose:
      - "8080"
    volumes:
      - whatsapp-data:/app/store
    restart: always
    networks:
      - whatsapp-network
    environment:
      - BRIDGE_PORT=8080
      - TZ=America/Argentina/Buenos_Aires
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M

  whatsapp-mcp-server:
    build:
      context: ./whatsapp-mcp-server
      dockerfile: Dockerfile
    image: rhv044/whatsapp-mcp-server:prod
    container_name: whatsapp-mcp-server
    expose:
      - "3000"
    volumes:
      - whatsapp-data:/app/store
    depends_on:
      - whatsapp-bridge
    restart: always
    networks:
      - whatsapp-network
    environment:
      - WHATSAPP_BRIDGE_URL=http://whatsapp-bridge:8080
      - MESSAGES_DB_PATH=/app/store/messages.db
      - PYTHONUNBUFFERED=1
      - TZ=America/Argentina/Buenos_Aires
    stdin_open: true
    tty: true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 64M

  nginx:
    image: nginx:alpine
    container_name: whatsapp-nginx
    ports:
      - "8443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro
    depends_on:
      - whatsapp-mcp-server
    restart: always
    networks:
      - whatsapp-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  certbot:
    image: certbot/certbot
    container_name: whatsapp-certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    restart: always
    networks:
      - whatsapp-network

volumes:
  whatsapp-data:
    driver: local 

networks:
  whatsapp-network:
    driver: bridge
